import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { useUser } from "@clerk/nextjs";

const ProfilePage: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser();
  api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          Profile View
        </div>
      </main>
    </>
  );
};

export default ProfilePage;
