name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://example.com"
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "example_clerk_key"
  CLERK_SECRET_KEY: "example_clerk_secret"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
